// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowTime.Context;

#nullable disable

namespace ShowTime.Migrations
{
    [DbContext(typeof(ShowTimeContext))]
    [Migration("20250704081809_AddingFestivalBands")]
    partial class AddingFestivalBands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BandFestival", b =>
                {
                    b.Property<Guid>("BandsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FestivalsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BandsId", "FestivalsId");

                    b.HasIndex("FestivalsId");

                    b.ToTable("BandFestival");
                });

            modelBuilder.Entity("ShowTime.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("ShowTime.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ShowTime.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Festivals");
                });

            modelBuilder.Entity("ShowTime.Entities.FestivalBand", b =>
                {
                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FestivalId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("FestivalBands");
                });

            modelBuilder.Entity("BandFestival", b =>
                {
                    b.HasOne("ShowTime.Entities.Band", null)
                        .WithMany()
                        .HasForeignKey("BandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowTime.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowTime.Entities.Booking", b =>
                {
                    b.HasOne("ShowTime.Entities.Festival", "Festival")
                        .WithMany("Bookings")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("ShowTime.Entities.FestivalBand", b =>
                {
                    b.HasOne("ShowTime.Entities.Band", "Band")
                        .WithMany("FestivalBand")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowTime.Entities.Festival", "Festival")
                        .WithMany("FestivalBand")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("ShowTime.Entities.Band", b =>
                {
                    b.Navigation("FestivalBand");
                });

            modelBuilder.Entity("ShowTime.Entities.Festival", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FestivalBand");
                });
#pragma warning restore 612, 618
        }
    }
}
